# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-front

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of the artefact to deploy"
        type: string
        required: true
      version:
        description: "The version of dotnet to use"
        type: string
        required: true
      working-directory:
        description: "The path to the working directory"
        type: string
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "ARTIFACT_NAME: ${{ inputs.artifact-name }}"
          echo "VERSION: ${{ inputs.version }}"
          echo "WORKING_DIRECTORY: ${{ inputs.working-directory }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up node environement and use yarn as cache for faster builds
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.version }}

      - name: install npm packages
        run: yarn
        working-directory: ${{ inputs.working-directory }}

      # aucun tests pour le moment => - name: test
      # aucun tests pour le moment =>   run: yarn nx run client:test
      # aucun tests pour le moment =>   working-directory: ${{ inputs.working-directory }}

      - name: build
        run: yarn nx run client:build
        working-directory: ${{ inputs.working-directory }}

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/dist/apps/client
